ALTER TABLE hotels ADD COLUMN is_featured INTEGER DEFAULT 0;
ALTER TABLE hotels ADD COLUMN sort_order INTEGER DEFAULT 0;

ALTER TABLE rentals ADD COLUMN is_featured INTEGER DEFAULT 0;
ALTER TABLE rentals ADD COLUMN sort_order INTEGER DEFAULT 0;

ALTER TABLE guides ADD COLUMN is_featured INTEGER DEFAULT 0;
ALTER TABLE guides ADD COLUMN sort_order INTEGER DEFAULT 0;

ALTER TABLE study_tours ADD COLUMN is_featured INTEGER DEFAULT 0;
ALTER TABLE study_tours ADD COLUMN sort_order INTEGER DEFAULT 0;
